from enum import Enum


class UserRole(str, Enum):
    """System-level User Roles (RBAC)."""
    ADMIN = "ADMIN"
    INVESTIGATOR = "INVESTIGATOR"
    ANALYST = "ANALYST"
    VIEWER = "VIEWER"


class CaseStatus(str, Enum):
    """Controlled lifecycle statuses for forensic cases."""
    OPEN = "OPEN"
    ACTIVE = "ACTIVE"
    IN_PROGRESS = "IN_PROGRESS"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class CaseAccessRole(str, Enum):
    """Case-level authorization membership roles."""
    LEAD = "LEAD"
    CONTRIBUTOR = "CONTRIBUTOR"
    ANALYST = "ANALYST"
    VIEWER = "VIEWER"


class AuditAction(str, Enum):
    """Categorized audit event action identifiers."""
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT = "LOGOUT"
    USER_CREATE = "USER_CREATE"
    CASE_CREATE = "CASE_CREATE"
    CASE_UPDATE = "CASE_UPDATE"
    CASE_MEMBER_ADD = "CASE_MEMBER_ADD"
    CASE_MEMBER_UPDATE = "CASE_MEMBER_UPDATE"
    CASE_MEMBER_REMOVE = "CASE_MEMBER_REMOVE"
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    EVIDENCE_UPLOAD_STARTED = "EVIDENCE_UPLOAD_STARTED"
    EVIDENCE_UPLOAD_COMPLETED = "EVIDENCE_UPLOAD_COMPLETED"
    EVIDENCE_UPLOAD_FAILED = "EVIDENCE_UPLOAD_FAILED"
    EVIDENCE_VALIDATION_FAILED = "EVIDENCE_VALIDATION_FAILED"
    EVIDENCE_ACCESSED = "EVIDENCE_ACCESSED"
    EVIDENCE_DOWNLOADED = "EVIDENCE_DOWNLOADED"
    EVIDENCE_QUARANTINED = "EVIDENCE_QUARANTINED"
    INTEGRITY_VERIFICATION_STARTED = "INTEGRITY_VERIFICATION_STARTED"
    INTEGRITY_VERIFICATION_COMPLETED = "INTEGRITY_VERIFICATION_COMPLETED"
    INTEGRITY_MISMATCH_DETECTED = "INTEGRITY_MISMATCH_DETECTED"
    CUSTODY_CHAIN_VERIFICATION_COMPLETED = "CUSTODY_CHAIN_VERIFICATION_COMPLETED"
    UFDR_PROCESSING_STARTED = "UFDR_PROCESSING_STARTED"
    UFDR_PROCESSING_COMPLETED = "UFDR_PROCESSING_COMPLETED"
    UFDR_PROCESSING_FAILED = "UFDR_PROCESSING_FAILED"
    UFDR_PROCESSING_PARTIAL = "UFDR_PROCESSING_PARTIAL"
    PROCESSING_JOB_CREATED = "PROCESSING_JOB_CREATED"
    PROCESSING_JOB_STARTED = "PROCESSING_JOB_STARTED"
    PROCESSING_JOB_RETRIED = "PROCESSING_JOB_RETRIED"
    PROCESSING_JOB_CANCEL_REQUESTED = "PROCESSING_JOB_CANCEL_REQUESTED"
    PROCESSING_JOB_COMPLETED = "PROCESSING_JOB_COMPLETED"
    PROCESSING_JOB_PARTIAL = "PROCESSING_JOB_PARTIAL"
    PROCESSING_JOB_FAILED = "PROCESSING_JOB_FAILED"
    PROCESSING_JOB_CANCELLED = "PROCESSING_JOB_CANCELLED"
    NORMALIZATION_STARTED = "NORMALIZATION_STARTED"
    NORMALIZATION_COMPLETED = "NORMALIZATION_COMPLETED"
    NORMALIZATION_PARTIAL = "NORMALIZATION_PARTIAL"
    NORMALIZATION_FAILED = "NORMALIZATION_FAILED"
    FORENSIC_SEARCH_EXECUTED = "FORENSIC_SEARCH_EXECUTED"
    SEMANTIC_SEARCH_EXECUTED = "SEMANTIC_SEARCH_EXECUTED"
    EMBEDDING_JOB_CREATED = "EMBEDDING_JOB_CREATED"
    EMBEDDING_JOB_STARTED = "EMBEDDING_JOB_STARTED"
    EMBEDDING_JOB_COMPLETED = "EMBEDDING_JOB_COMPLETED"
    EMBEDDING_JOB_FAILED = "EMBEDDING_JOB_FAILED"
    VECTOR_INDEX_REBUILT = "VECTOR_INDEX_REBUILT"
    INVESTIGATION_QUERY_EXECUTED = "INVESTIGATION_QUERY_EXECUTED"
    RAG_QUERY_EXECUTED = "RAG_QUERY_EXECUTED"
    GRAPH_ANALYSIS_EXECUTED = "GRAPH_ANALYSIS_EXECUTED"
    GRAPH_SNAPSHOT_CREATED = "GRAPH_SNAPSHOT_CREATED"
    TIMELINE_GENERATED = "TIMELINE_GENERATED"
    ANOMALY_DETECTION_EXECUTED = "ANOMALY_DETECTION_EXECUTED"
    ANOMALY_JOB_CREATED = "ANOMALY_JOB_CREATED"
    ANOMALY_JOB_COMPLETED = "ANOMALY_JOB_COMPLETED"
    ANOMALY_JOB_FAILED = "ANOMALY_JOB_FAILED"
    REPORT_GENERATED = "REPORT_GENERATED"
    REPORT_APPROVED = "REPORT_APPROVED"
    REPORT_EXPORTED = "REPORT_EXPORTED"
    REPORT_REJECTED = "REPORT_REJECTED"
    REPORT_JOB_CREATED = "REPORT_JOB_CREATED"
    REPORT_JOB_COMPLETED = "REPORT_JOB_COMPLETED"
    REPORT_JOB_FAILED = "REPORT_JOB_FAILED"


class EvidenceStatus(str, Enum):
    """Controlled lifecycle statuses for forensic evidence files."""
    UPLOADING = "UPLOADING"
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    VALID = "VALID"
    INVALID = "INVALID"
    FAILED = "FAILED"
    QUARANTINED = "QUARANTINED"
    PROCESSED = "PROCESSED"


class IntegrityStatus(str, Enum):
    """Cryptographic integrity state of stored original evidence."""
    UNKNOWN = "UNKNOWN"
    VALID = "VALID"
    MISMATCH = "MISMATCH"
    MISSING = "MISSING"
    ERROR = "ERROR"


class CustodyEventType(str, Enum):
    """Controlled chain-of-custody lifecycle event types."""
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    EVIDENCE_HASHED = "EVIDENCE_HASHED"
    EVIDENCE_VALIDATED = "EVIDENCE_VALIDATED"
    EVIDENCE_ACCESSED = "EVIDENCE_ACCESSED"
    EVIDENCE_DOWNLOADED = "EVIDENCE_DOWNLOADED"
    INTEGRITY_VERIFIED = "INTEGRITY_VERIFIED"
    INTEGRITY_MISMATCH = "INTEGRITY_MISMATCH"
    EVIDENCE_PROCESSING_STARTED = "EVIDENCE_PROCESSING_STARTED"
    EVIDENCE_PROCESSING_COMPLETED = "EVIDENCE_PROCESSING_COMPLETED"
    EVIDENCE_NORMALIZATION_STARTED = "EVIDENCE_NORMALIZATION_STARTED"
    EVIDENCE_NORMALIZATION_COMPLETED = "EVIDENCE_NORMALIZATION_COMPLETED"
    EVIDENCE_QUARANTINED = "EVIDENCE_QUARANTINED"
    EVIDENCE_ARCHIVED = "EVIDENCE_ARCHIVED"


class JobType(str, Enum):
    """Asynchronous forensic processing job categories."""
    UFDR_PARSE = "UFDR_PARSE"
    NORMALIZATION = "NORMALIZATION"
    INDEXING = "INDEXING"
    EMBEDDING = "EMBEDDING"
    ANALYSIS = "ANALYSIS"
    REPORT_GENERATION = "REPORT_GENERATION"


class JobPriority(str, Enum):
    """Execution priority levels for queue scheduling."""
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"


class JobStatus(str, Enum):
    """Lifecycle states of forensic processing jobs."""
    QUEUED = "QUEUED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    RETRYING = "RETRYING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"


class ProcessingStage(str, Enum):
    """Granular execution stages during processing."""
    VALIDATING = "VALIDATING"
    INSPECTING_ARCHIVE = "INSPECTING_ARCHIVE"
    PARSING = "PARSING"
    PERSISTING = "PERSISTING"
    FETCHING_RAW = "FETCHING_RAW"
    NORMALIZING = "NORMALIZING"
    FINALIZING = "FINALIZING"
    COMPLETED = "COMPLETED"


class ArtifactType(str, Enum):
    """Categorization for raw and canonical forensic artifacts extracted from UFDR containers."""
    CALL = "CALL"
    MESSAGE = "MESSAGE"
    CONTACT = "CONTACT"
    LOCATION = "LOCATION"
    BROWSER = "BROWSER"
    APPLICATION = "APPLICATION"
    FILESYSTEM = "FILESYSTEM"
    CALENDAR = "CALENDAR"
    SOCIAL = "SOCIAL"
    DEVICE_EVENT = "DEVICE_EVENT"


class TimestampPrecision(str, Enum):
    """Granularity of extracted timestamps."""
    YEAR = "YEAR"
    MONTH = "MONTH"
    DAY = "DAY"
    HOUR = "HOUR"
    MINUTE = "MINUTE"
    SECOND = "SECOND"
    MILLISECOND = "MILLISECOND"
    UNKNOWN = "UNKNOWN"


class TimestampStatus(str, Enum):
    """Quality and validity status of extracted event timestamps."""
    VALID = "VALID"
    INVALID = "INVALID"
    UNKNOWN = "UNKNOWN"


class DataQualityStatus(str, Enum):
    """Overall data quality classification for canonical records."""
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    INVALID = "INVALID"
    UNKNOWN = "UNKNOWN"


class InvestigationIntent(str, Enum):
    """Configurable intent taxonomy for natural-language forensic queries."""
    PERSON_LOOKUP = "PERSON_LOOKUP"
    EVENT_RETRIEVAL = "EVENT_RETRIEVAL"
    COMMUNICATION_ANALYSIS = "COMMUNICATION_ANALYSIS"
    TEMPORAL_INVESTIGATION = "TEMPORAL_INVESTIGATION"
    DEVICE_LOOKUP = "DEVICE_LOOKUP"
    LOCATION_LOOKUP = "LOCATION_LOOKUP"
    APPLICATION_ACTIVITY = "APPLICATION_ACTIVITY"
    GENERAL_EVIDENCE_SEARCH = "GENERAL_EVIDENCE_SEARCH"
    UNKNOWN = "UNKNOWN"


class EntityType(str, Enum):
    """Categorization for extracted forensic entity references."""
    PERSON = "PERSON"
    PHONE_NUMBER = "PHONE_NUMBER"
    EMAIL = "EMAIL"
    ACCOUNT = "ACCOUNT"
    DEVICE = "DEVICE"
    APPLICATION = "APPLICATION"
    LOCATION = "LOCATION"
    DATE = "DATE"
    TIME = "TIME"
    DATE_RANGE = "DATE_RANGE"
    URL = "URL"
    FILE = "FILE"
    ARTIFACT_TYPE = "ARTIFACT_TYPE"


class SearchMode(str, Enum):
    """Retrieval execution modes for forensic search."""
    EXACT = "EXACT"
    LEXICAL = "LEXICAL"
    SEMANTIC = "SEMANTIC"
    HYBRID = "HYBRID"


class EmbeddingStatus(str, Enum):
    """Lifecycle states of canonical record vector embeddings."""
    NOT_GENERATED = "NOT_GENERATED"
    QUEUED = "QUEUED"
    GENERATING = "GENERATING"
    READY = "READY"
    STALE = "STALE"
    FAILED = "FAILED"
    NOT_EMBEDDABLE = "NOT_EMBEDDABLE"


class NodeType(str, Enum):
    """Normalized graph node entity classifications."""
    PERSON = "PERSON"
    PHONE_NUMBER = "PHONE_NUMBER"
    EMAIL = "EMAIL"
    ACCOUNT = "ACCOUNT"
    DEVICE = "DEVICE"
    APPLICATION = "APPLICATION"


class EdgeType(str, Enum):
    """Normalized graph communication edge interaction categories."""
    CALL = "CALL"
    SMS = "SMS"
    MMS = "MMS"
    MESSAGE = "MESSAGE"
    EMAIL = "EMAIL"
    OTHER_COMMUNICATION = "OTHER_COMMUNICATION"


class GraphMetricType(str, Enum):
    """Mathematical graph and centrality metric types."""
    DEGREE = "DEGREE"
    IN_DEGREE = "IN_DEGREE"
    OUT_DEGREE = "OUT_DEGREE"
    WEIGHTED_DEGREE = "WEIGHTED_DEGREE"
    BETWEENNESS = "BETWEENNESS"
    CLOSENESS = "CLOSENESS"
    PAGERANK = "PAGERANK"


class CommunityAlgorithm(str, Enum):
    """Deterministic community detection algorithms."""
    LOUVAIN = "LOUVAIN"
    GREEDY_MODULARITY = "GREEDY_MODULARITY"


class AnomalyType(str, Enum):
    """Categorized behavioral and temporal anomaly patterns."""
    COMMUNICATION_BURST = "COMMUNICATION_BURST"
    COMMUNICATION_INACTIVITY = "COMMUNICATION_INACTIVITY"
    UNUSUAL_APPLICATION_ACTIVITY = "UNUSUAL_APPLICATION_ACTIVITY"
    UNUSUAL_EVENT_FREQUENCY = "UNUSUAL_EVENT_FREQUENCY"
    UNUSUAL_TIME_OF_DAY = "UNUSUAL_TIME_OF_DAY"
    UNUSUAL_CONTACT_DIVERSITY = "UNUSUAL_CONTACT_DIVERSITY"
    UNUSUAL_INTER_EVENT_TIMING = "UNUSUAL_INTER_EVENT_TIMING"
    UNUSUAL_LOCATION_TRANSITION = "UNUSUAL_LOCATION_TRANSITION"


class AnomalyClassification(str, Enum):
    """Statistical binary classification state."""
    NORMAL = "NORMAL"
    ANOMALOUS = "ANOMALOUS"


class AnomalySeverity(str, Enum):
    """Neutral statistical severity tiers for detected anomalies."""
    LOW_ANOMALY = "LOW_ANOMALY"
    MODERATE_ANOMALY = "MODERATE_ANOMALY"
    HIGH_ANOMALY = "HIGH_ANOMALY"


class AnomalyAlgorithm(str, Enum):
    """Supported anomaly detection algorithms."""
    ISOLATION_FOREST = "ISOLATION_FOREST"
    STATISTICAL_ZSCORE = "STATISTICAL_ZSCORE"
    ROLLING_BASELINE = "ROLLING_BASELINE"


class TemporalWindowSize(str, Enum):
    """Supported temporal window bucket durations."""
    ONE_MINUTE = "1m"
    FIVE_MINUTES = "5m"
    FIFTEEN_MINUTES = "15m"
    THIRTY_MINUTES = "30m"
    ONE_HOUR = "1h"
    SIX_HOURS = "6h"
    TWENTY_FOUR_HOURS = "24h"


class BaselineType(str, Enum):
    """Configurable baseline calculation modes."""
    FULL_CASE = "FULL_CASE"
    PREVIOUS_PERIOD = "PREVIOUS_PERIOD"
    ROLLING_WINDOW = "ROLLING_WINDOW"
    HISTORICAL_ENTITY = "HISTORICAL_ENTITY"


class ReportType(str, Enum):
    """Supported forensic investigation report categories."""
    CASE_SUMMARY = "CASE_SUMMARY"
    EVIDENCE_SUMMARY = "EVIDENCE_SUMMARY"
    TIMELINE_REPORT = "TIMELINE_REPORT"
    COMMUNICATION_ANALYSIS_REPORT = "COMMUNICATION_ANALYSIS_REPORT"
    ANOMALY_ANALYSIS_REPORT = "ANOMALY_ANALYSIS_REPORT"
    INVESTIGATION_QUERY_REPORT = "INVESTIGATION_QUERY_REPORT"
    COMPREHENSIVE_FORENSIC_ANALYSIS_REPORT = "COMPREHENSIVE_FORENSIC_ANALYSIS_REPORT"


class ReportStatus(str, Enum):
    """Controlled lifecycle states for generated investigation reports."""
    DRAFT = "DRAFT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    EXPORTED = "EXPORTED"
    ARCHIVED = "ARCHIVED"


class FindingType(str, Enum):
    """Categorized forensic finding types."""
    TIMELINE_EVENT = "TIMELINE_EVENT"
    COMMUNICATION_PATTERN = "COMMUNICATION_PATTERN"
    STATISTICAL_ANOMALY = "STATISTICAL_ANOMALY"
    EVIDENCE_CORRELATION = "EVIDENCE_CORRELATION"
    INVESTIGATION_QUERY_RESULT = "INVESTIGATION_QUERY_RESULT"
    ANALYST_NOTE = "ANALYST_NOTE"


class ExportFormat(str, Enum):
    """Supported export output document formats."""
    PDF = "PDF"
    JSON = "JSON"
    CSV = "CSV"
    HTML = "HTML"





