"""create_evidence_table

Revision ID: 01cef93c2693
Revises: 4ab5bdad3f33
Create Date: 2026-09-30 22:44:49.505855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cef93c2693'
down_revision: Union[str, Sequence[str], None] = '4ab5bdad3f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path_or_key', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('detected_mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'UPLOADED', 'VALIDATING', 'VALID', 'INVALID', 'FAILED', 'QUARANTINED', name='evidence_status_enum', native_enum=False), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_sha256_hash'), 'evidence', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_evidence_status'), 'evidence', ['status'], unique=False)
    op.create_index(op.f('ix_evidence_uploaded_at'), 'evidence', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_evidence_uploaded_by'), 'evidence', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_uploaded_by'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_uploaded_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_status'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_sha256_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
