"""create_custody_events_table_and_integrity_fields

Revision ID: 7b7d07c98a98
Revises: 01cef93c2693
Create Date: 2026-09-30 23:12:58.814847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7d07c98a98'
down_revision: Union[str, Sequence[str], None] = '01cef93c2693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_custody_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('EVIDENCE_UPLOADED', 'EVIDENCE_HASHED', 'EVIDENCE_VALIDATED', 'EVIDENCE_ACCESSED', 'EVIDENCE_DOWNLOADED', 'INTEGRITY_VERIFIED', 'INTEGRITY_MISMATCH', 'EVIDENCE_QUARANTINED', 'EVIDENCE_ARCHIVED', name='custody_event_type_enum', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('previous_event_id', sa.Uuid(), nullable=True),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_event_id'], ['evidence_custody_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_custody_evidence_sequence', 'evidence_custody_events', ['evidence_id', 'sequence_number'], unique=False)
    op.create_index(op.f('ix_evidence_custody_events_actor_user_id'), 'evidence_custody_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_evidence_custody_events_case_id'), 'evidence_custody_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_custody_events_event_hash'), 'evidence_custody_events', ['event_hash'], unique=False)
    op.create_index(op.f('ix_evidence_custody_events_event_type'), 'evidence_custody_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_evidence_custody_events_evidence_id'), 'evidence_custody_events', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_custody_events_timestamp'), 'evidence_custody_events', ['timestamp'], unique=False)
    op.add_column('evidence', sa.Column('integrity_status', sa.Enum('UNKNOWN', 'VALID', 'MISMATCH', 'MISSING', 'ERROR', name='integrity_status_enum', native_enum=False), nullable=False, server_default='VALID'))
    op.add_column('evidence', sa.Column('last_integrity_check_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_evidence_integrity_status'), 'evidence', ['integrity_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_integrity_status'), table_name='evidence')
    op.drop_column('evidence', 'last_integrity_check_at')
    op.drop_column('evidence', 'integrity_status')
    op.drop_index(op.f('ix_evidence_custody_events_timestamp'), table_name='evidence_custody_events')
    op.drop_index(op.f('ix_evidence_custody_events_evidence_id'), table_name='evidence_custody_events')
    op.drop_index(op.f('ix_evidence_custody_events_event_type'), table_name='evidence_custody_events')
    op.drop_index(op.f('ix_evidence_custody_events_event_hash'), table_name='evidence_custody_events')
    op.drop_index(op.f('ix_evidence_custody_events_case_id'), table_name='evidence_custody_events')
    op.drop_index(op.f('ix_evidence_custody_events_actor_user_id'), table_name='evidence_custody_events')
    op.drop_index('ix_custody_evidence_sequence', table_name='evidence_custody_events')
    op.drop_table('evidence_custody_events')
    # ### end Alembic commands ###
