"""create_processing_jobs_and_raw_artifacts_tables

Revision ID: b2c4e293d042
Revises: 7b7d07c98a98
Create Date: 2026-09-30 23:30:54.103719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c4e293d042'
down_revision: Union[str, Sequence[str], None] = '7b7d07c98a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('UFDR_PARSE', 'NORMALIZATION', 'INDEXING', 'EMBEDDING', 'ANALYSIS', 'REPORT_GENERATION', name='job_type_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status_enum', native_enum=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('files_total', sa.Integer(), nullable=False),
    sa.Column('files_processed', sa.Integer(), nullable=False),
    sa.Column('artifacts_total', sa.Integer(), nullable=False),
    sa.Column('warnings_count', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_jobs_case_evidence', 'processing_jobs', ['case_id', 'evidence_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_case_id'), 'processing_jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_created_at'), 'processing_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_created_by'), 'processing_jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_processing_jobs_evidence_id'), 'processing_jobs', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index('ix_processing_jobs_status_type', 'processing_jobs', ['status', 'job_type'], unique=False)
    op.create_table('raw_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('processing_job_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('CALL', 'MESSAGE', 'CONTACT', 'LOCATION', 'BROWSER', 'APPLICATION', 'FILESYSTEM', name='artifact_type_enum', native_enum=False), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('record_identifier', sa.String(length=255), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_artifacts_artifact_type'), 'raw_artifacts', ['artifact_type'], unique=False)
    op.create_index('ix_raw_artifacts_case_evidence_type', 'raw_artifacts', ['case_id', 'evidence_id', 'artifact_type'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_case_id'), 'raw_artifacts', ['case_id'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_created_at'), 'raw_artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_evidence_id'), 'raw_artifacts', ['evidence_id'], unique=False)
    op.create_index('ix_raw_artifacts_evidence_source', 'raw_artifacts', ['evidence_id', 'source_file'], unique=False)
    op.create_index('ix_raw_artifacts_job_type', 'raw_artifacts', ['processing_job_id', 'artifact_type'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_processing_job_id'), 'raw_artifacts', ['processing_job_id'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_record_identifier'), 'raw_artifacts', ['record_identifier'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_source_file'), 'raw_artifacts', ['source_file'], unique=False)
    op.create_index('ix_raw_artifacts_traceability', 'raw_artifacts', ['evidence_id', 'record_identifier'], unique=False)
    with op.batch_alter_table('evidence_custody_events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('EVIDENCE_UPLOADED', 'EVIDENCE_HASHED', 'EVIDENCE_VALIDATED', 'EVIDENCE_ACCESSED', 'EVIDENCE_DOWNLOADED', 'INTEGRITY_VERIFIED', 'INTEGRITY_MISMATCH', 'EVIDENCE_PROCESSING_STARTED', 'EVIDENCE_PROCESSING_COMPLETED', 'EVIDENCE_QUARANTINED', 'EVIDENCE_ARCHIVED', name='custody_event_type_enum', native_enum=False),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evidence_custody_events', 'event_type',
               existing_type=sa.Enum('EVIDENCE_UPLOADED', 'EVIDENCE_HASHED', 'EVIDENCE_VALIDATED', 'EVIDENCE_ACCESSED', 'EVIDENCE_DOWNLOADED', 'INTEGRITY_VERIFIED', 'INTEGRITY_MISMATCH', 'EVIDENCE_PROCESSING_STARTED', 'EVIDENCE_PROCESSING_COMPLETED', 'EVIDENCE_QUARANTINED', 'EVIDENCE_ARCHIVED', name='custody_event_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index('ix_raw_artifacts_traceability', table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_source_file'), table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_record_identifier'), table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_processing_job_id'), table_name='raw_artifacts')
    op.drop_index('ix_raw_artifacts_job_type', table_name='raw_artifacts')
    op.drop_index('ix_raw_artifacts_evidence_source', table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_evidence_id'), table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_created_at'), table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_case_id'), table_name='raw_artifacts')
    op.drop_index('ix_raw_artifacts_case_evidence_type', table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_artifact_type'), table_name='raw_artifacts')
    op.drop_table('raw_artifacts')
    op.drop_index('ix_processing_jobs_status_type', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_evidence_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_created_by'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_created_at'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_case_id'), table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_case_evidence', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    # ### end Alembic commands ###
