from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class EvidenceContextItem(BaseModel):
    """
    Standardized forensic context item passed to the Evidence Context Builder.
    """
    evidence_tag: str = Field(..., description="Unique tag within context, e.g., 'EVIDENCE-001'")
    evidence_id: str = Field(..., description="Forensic evidence primary ID or canonical ID")
    canonical_id: str = Field(..., description="Canonical database ID for the record")
    raw_artifact_id: Optional[str] = Field(None, description="Reference to raw artifact MongoDB/file ID")
    case_id: str = Field(..., description="Case ID for strict isolation verification")
    artifact_type: str = Field(..., description="Canonical artifact category (message, call, contact, etc.)")
    source_application: Optional[str] = Field(None, description="App origin, e.g., WhatsApp, Signal, SMS")
    timestamp: Optional[str] = Field(None, description="Event timestamp in ISO string format")
    sender: Optional[str] = Field(None, description="Sender identifier or phone/email")
    receiver: Optional[str] = Field(None, description="Receiver identifier or phone/email")
    content: str = Field(..., description="Text content or transcription of the evidence record")
    source_file: Optional[str] = Field(None, description="Source archive or file path")
    record_identifier: Optional[str] = Field(None, description="Original record ID within source")
    relevance_score: Optional[float] = Field(None, description="Ranking or hybrid search score")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Safe forensic metadata")


class EvidenceCitation(BaseModel):
    """
    Structured evidence citation referencing verified forensic records.
    """
    citation_tag: str = Field(..., description="Tag cited by the model, e.g., 'EVIDENCE-001'")
    evidence_id: str = Field(..., description="Primary evidence UUID/ID")
    canonical_id: str = Field(..., description="Canonical evidence record ID")
    artifact_type: str = Field(..., description="Artifact category")
    source_application: Optional[str] = Field(None, description="Source application")
    timestamp: Optional[str] = Field(None, description="Preserved event timestamp")
    sender: Optional[str] = Field(None, description="Sender identity if present")
    receiver: Optional[str] = Field(None, description="Receiver identity if present")
    reason: str = Field(..., description="Specific grounding rationale or claim supported")
    content_snippet: str = Field(..., description="Verbatim content snippet from the source record")
    is_verified: bool = Field(True, description="Whether citation was successfully verified against context")


class ConflictingRecord(BaseModel):
    """
    Details of conflicting forensic evidence discovered during retrieval.
    """
    field_name: str = Field(..., description="Contested field (e.g., 'timestamp', 'sender')")
    records: List[Dict[str, Any]] = Field(..., description="Conflicting context records")
    conflict_description: str = Field(..., description="Explanation of the discrepancy")


class RAGValidationReport(BaseModel):
    """
    Report generated by the Citation and Hallucination Validation Layer.
    """
    is_valid: bool = Field(..., description="Overall validity of the generated response")
    total_citations_found: int = Field(0, description="Total citations extracted from model output")
    valid_citations: List[str] = Field(default_factory=list, description="Verified citation tags")
    invalid_citations: List[str] = Field(default_factory=list, description="Nonexistent or out-of-context citation tags")
    cross_case_violations: List[str] = Field(default_factory=list, description="Detected cross-case leaks")
    unsupported_claims: List[str] = Field(default_factory=list, description="Claims flagged without evidence support")
    validation_notes: str = Field("", description="Summary notes on validation result")


class RAGQueryRequest(BaseModel):
    """
    Investigator natural language inquiry request.
    """
    query: str = Field(..., min_length=2, max_length=1000, description="Natural language forensic query")
    conversation_id: Optional[str] = Field(None, description="Optional conversation session ID")
    max_context_records: Optional[int] = Field(None, ge=1, le=50, description="Max evidence items in context window")
    include_citations: bool = Field(True, description="Whether to extract and validate evidence citations")
    focus_artifact_types: Optional[List[str]] = Field(None, description="Optional filter to restrict artifact types")
    provider_override: Optional[str] = Field(None, description="Optional LLM provider override")


class ReproducibilityMetadata(BaseModel):
    """
    Forensic reproducibility metadata for auditing and verification.
    """
    query: str
    case_id: str
    llm_provider: str
    llm_model: str
    temperature: float
    prompt_version: str
    rag_version: str
    retrieval_top_k: int
    context_record_count: int
    retrieved_evidence_ids: List[str]
    timestamp: str


class RAGQueryResponse(BaseModel):
    """
    Evidence-grounded response returned to the investigator.
    """
    query_id: str = Field(..., description="Unique investigation query tracking ID")
    case_id: str = Field(..., description="Active case ID")
    conversation_id: str = Field(..., description="Session conversation ID")
    query: str = Field(..., description="Investigator original query")
    investigation_plan: Optional[Dict[str, Any]] = Field(None, description="Phase 11 NLP investigation plan")
    answer: str = Field(..., description="Evidence-grounded structured answer")
    evidence_references: List[EvidenceCitation] = Field(default_factory=list, description="Verified citations")
    conflicting_evidence: List[ConflictingRecord] = Field(default_factory=list, description="Conflicting records if any")
    uncertainty: Optional[str] = Field(None, description="Uncertainty disclaimer or observations")
    limitations: Optional[str] = Field(None, description="Investigation scope limitations")
    is_insufficient_evidence: bool = Field(False, description="Flag indicating evidence was insufficient to answer")
    validation_report: RAGValidationReport = Field(..., description="Citation validation result")
    reproducibility: ReproducibilityMetadata = Field(..., description="Metadata for reproducing output")
    audit_log_id: Optional[str] = Field(None, description="Reference audit log ID")
    latency_ms: float = Field(..., description="Total pipeline latency in milliseconds")


class RAGConversationMessage(BaseModel):
    """
    A single turn in an investigative conversation.
    """
    message_id: str
    case_id: str
    role: str  # "user" | "assistant"
    content: str
    timestamp: str
    evidence_references: Optional[List[EvidenceCitation]] = None


class RAGConversationHistory(BaseModel):
    """
    Full conversation history for a case investigation session.
    """
    conversation_id: str
    case_id: str
    messages: List[RAGConversationMessage] = Field(default_factory=list)
    created_at: str
    updated_at: str
