import hashlib
import io
import logging
from typing import Any, Dict, List, Optional
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from backend.app.schemas.report import ForensicReportDocument

logger = logging.getLogger(__name__)


class NumberedCanvas:
    """Helper to record page numbers and forensic headers."""
    pass


class ForensicPDFGenerator:
    """
    Forensic Investigation Report PDF Generator.
    Produces court-ready, evidence-grounded PDF reports with strict typography,
    structured tables, citation references, and tamper-evident SHA-256 verification signatures.
    """

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        self.title_style = ParagraphStyle(
            "DocTitle",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=colors.HexColor("#111827"),
            spaceAfter=6,
        )
        self.subtitle_style = ParagraphStyle(
            "DocSubtitle",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#4B5563"),
            spaceAfter=14,
        )
        self.h1_style = ParagraphStyle(
            "Heading1_Custom",
            parent=self.styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#1F2937"),
            spaceBefore=12,
            spaceAfter=6,
        )
        self.body_style = ParagraphStyle(
            "Body_Custom",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#374151"),
            spaceAfter=4,
        )
        self.mono_style = ParagraphStyle(
            "Mono_Custom",
            parent=self.styles["Normal"],
            fontName="Courier",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#111827"),
        )
        self.status_badge_style = ParagraphStyle(
            "StatusBadge",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#0284C7"),
            alignment=2,  # Right aligned
        )

    def generate_pdf_bytes(self, doc: ForensicReportDocument) -> bytes:
        """Render complete forensic report document into PDF bytes."""
        buffer = io.BytesIO()
        pdf = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=36,
        )

        story = []

        # --- Top Header ---
        header_table_data = [
            [
                Paragraph(f"<b>CASE: {doc.case_info.case_number}</b>", self.body_style),
                Paragraph(f"<b>STATUS: {doc.status.value} (v{doc.version})</b>", self.status_badge_style),
            ]
        ]
        t_header = Table(header_table_data, colWidths=[300, 240])
        t_header.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ]
            )
        )
        story.append(t_header)
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0284C7"), spaceAfter=10))

        # Title
        story.append(Paragraph(doc.title, self.title_style))
        story.append(
            Paragraph(
                f"Generated by {doc.generated_by_name} on {doc.generated_at.replace('T', ' ')[:19]} UTC | Report ID: {doc.report_id}",
                self.subtitle_style,
            )
        )

        # --- Section 1: Case Information ---
        story.append(Paragraph("1. Case & Investigation Information", self.h1_style))
        case_info_data = [
            [Paragraph("<b>Case Title:</b>", self.body_style), Paragraph(doc.case_info.title, self.body_style)],
            [Paragraph("<b>Case Number:</b>", self.body_style), Paragraph(doc.case_info.case_number, self.body_style)],
            [Paragraph("<b>Lead Officer:</b>", self.body_style), Paragraph(doc.case_info.lead_investigator or "N/A", self.body_style)],
            [Paragraph("<b>Report Type:</b>", self.body_style), Paragraph(doc.report_type.value, self.body_style)],
        ]
        t_case = Table(case_info_data, colWidths=[120, 420])
        t_case.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(t_case)
        story.append(Spacer(1, 10))

        # --- Section 2: Evidence Inventory ---
        if doc.evidence_inventory:
            story.append(Paragraph("2. Evidence Inventory & Cryptographic Integrity", self.h1_style))
            ev_headers = ["Evidence #", "Original Filename", "SHA-256 Hash", "Integrity", "Artifacts"]
            ev_rows = [[Paragraph(f"<b>{h}</b>", self.body_style) for h in ev_headers]]
            for ev in doc.evidence_inventory:
                hash_short = ev.sha256_hash[:16] + "..." if len(ev.sha256_hash) > 16 else ev.sha256_hash
                ev_rows.append(
                    [
                        Paragraph(ev.evidence_number, self.body_style),
                        Paragraph(ev.original_filename, self.body_style),
                        Paragraph(hash_short, self.mono_style),
                        Paragraph(ev.integrity_status, self.body_style),
                        Paragraph(str(ev.artifact_count), self.body_style),
                    ]
                )
            t_ev = Table(ev_rows, colWidths=[70, 130, 160, 110, 70])
            t_ev.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E5E7EB")),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
                        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                        ("TOPPADDING", (0, 0), (-1, -1), 3),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ]
                )
            )
            story.append(t_ev)
            story.append(Spacer(1, 10))

        # --- Section 3: Findings ---
        if doc.findings:
            story.append(Paragraph("3. Forensic Findings & Citations", self.h1_style))
            for f in doc.findings:
                finding_box = [
                    [Paragraph(f"<b>[{f.finding_id}] {f.title}</b> ({f.finding_type.value})", self.body_style)],
                    [Paragraph(f.description, self.body_style)],
                ]
                if f.citations:
                    cits_str = ", ".join([f"<b>{c.citation_id}</b> ({c.evidence_number})" for c in f.citations])
                    finding_box.append([Paragraph(f"<b>Citations:</b> {cits_str}", self.body_style)])
                t_f = Table(finding_box, colWidths=[540])
                t_f.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F3F4F6")),
                            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
                            ("LEFTPADDING", (0, 0), (-1, -1), 6),
                            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                            ("TOPPADDING", (0, 0), (-1, -1), 4),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        ]
                    )
                )
                story.append(t_f)
                story.append(Spacer(1, 6))
            story.append(Spacer(1, 6))

        # --- Section 4: Timeline Highlights ---
        if doc.timeline_section:
            story.append(Paragraph("4. Unified Chronological Timeline Highlights", self.h1_style))
            tl_headers = ["Timestamp (UTC)", "Event", "App", "Participants / Details", "Citation"]
            tl_rows = [[Paragraph(f"<b>{h}</b>", self.body_style) for h in tl_headers]]
            for entry in doc.timeline_section[:30]:  # Cap at top 30 for PDF page budgeting
                ts_str = entry.timestamp.replace("T", " ")[:19]
                actors = f"{entry.actor or ''} → {entry.target or ''}".strip(" →")
                details = f"{actors} | {entry.content_summary or ''}".strip(" |")
                tl_rows.append(
                    [
                        Paragraph(ts_str, self.mono_style),
                        Paragraph(entry.event_type, self.body_style),
                        Paragraph(entry.application or "-", self.body_style),
                        Paragraph(details[:100], self.body_style),
                        Paragraph(entry.citation_ref, self.body_style),
                    ]
                )
            t_tl = Table(tl_rows, colWidths=[105, 65, 75, 230, 65])
            t_tl.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E5E7EB")),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("TOPPADDING", (0, 0), (-1, -1), 3),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ]
                )
            )
            story.append(t_tl)
            story.append(Spacer(1, 10))

        # --- Section 5: Communication Graph Analysis ---
        if doc.graph_section:
            story.append(Paragraph("5. Communication Network & Social Network Analysis (SNA)", self.h1_style))
            gs = doc.graph_section
            graph_data = [
                [Paragraph(f"<b>Total Entities (Nodes):</b> {gs.total_nodes}", self.body_style), Paragraph(f"<b>Total Interactions (Edges):</b> {gs.total_edges}", self.body_style)],
                [Paragraph(f"<b>Network Density:</b> {gs.density:.4f}", self.body_style), Paragraph(f"<b>Detected Communities:</b> {gs.detected_communities_count}", self.body_style)],
            ]
            t_graph = Table(graph_data, colWidths=[270, 270])
            t_graph.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
                        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ]
                )
            )
            story.append(t_graph)
            story.append(Spacer(1, 10))

        # --- Section 6: Statistical Anomaly Findings ---
        if doc.anomaly_section:
            story.append(Paragraph("6. Statistical Anomaly & Pattern Findings", self.h1_style))
            anom_headers = ["Window", "Anomaly Type", "Score", "Statistical Deviation Explanation", "Ref"]
            anom_rows = [[Paragraph(f"<b>{h}</b>", self.body_style) for h in anom_headers]]
            for anom in doc.anomaly_section[:10]:
                anom_rows.append(
                    [
                        Paragraph(anom.time_window[:16].replace("T", " "), self.mono_style),
                        Paragraph(anom.anomaly_type.replace("_", " "), self.body_style),
                        Paragraph(f"{anom.anomaly_score:.2f}", self.body_style),
                        Paragraph(anom.factual_explanation, self.body_style),
                        Paragraph(", ".join(anom.citation_refs[:2]), self.body_style),
                    ]
                )
            t_anom = Table(anom_rows, colWidths=[90, 110, 45, 235, 60])
            t_anom.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E5E7EB")),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("TOPPADDING", (0, 0), (-1, -1), 3),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ]
                )
            )
            story.append(t_anom)
            story.append(Spacer(1, 10))

        # --- Section 7: Limitations & Analyst Notes ---
        story.append(Paragraph("7. Forensic Limitations & Observations", self.h1_style))
        lim_list = doc.limitations if doc.limitations else ["No structural anomalies or evidence limitations reported."]
        for lim in lim_list:
            story.append(Paragraph(f"• {lim}", self.body_style))

        if doc.analyst_notes:
            story.append(Paragraph("<b>Analyst Notes:</b>", self.body_style))
            story.append(Paragraph(doc.analyst_notes, self.body_style))

        story.append(Spacer(1, 14))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#9CA3AF"), spaceAfter=8))

        # Signature / Verification Block
        hash_val = doc.report_hash or "CALCULATING_ON_EXPORT"
        sig_data = [
            [Paragraph("<b>REPORT INTEGRITY SHA-256 SIGNATURE:</b>", self.mono_style)],
            [Paragraph(f"SHA-256: {hash_val}", self.mono_style)],
            [Paragraph(f"Software Version: {doc.reproducibility.get('software_version', '1.0.0')} | Tamper-evident verified record.", self.body_style)],
        ]
        t_sig = Table(sig_data, colWidths=[540])
        t_sig.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F3F4F6")),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#9CA3AF")),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ]
            )
        )
        story.append(t_sig)

        pdf.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes


pdf_generator = ForensicPDFGenerator()
